01_ped_liver_QC_with_dropletQC_SCINA_IFALD.R
	01_ped_liver_QC_with_dropletQC_SCINA_IFALD_PBMC_only.R
	#02_IFALD_ped_adult_fetal_integration.R
	cellxgene_ped_adult_ifald.R

	03_PBMC_correction_IFALD
	03_IFALD_Tcells.R
03_IFALD_myeloid.R
03_IFALD_HSC.R
03_IFALD_Bcells.R

	04_differential_expression_montecarlo.R
	04_differential_expression_montecarlo_withFetal_IFALD.R

	05_differential_expression_age_interpretation.R

	06_cell_composistion.R
04_Fetal_PCA_roughwork

cpdb